version: '3.9'

services:
  backend_api:
    build: .
    container_name: bakckend_api
    command: >
      bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8002"
    ports:
      - '8888:8002'
    volumes:
      - ./src/core/.env.docker:/app/src/core/.env
    networks:
      - backend_api
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    expose:
      - '6379'
    ports:
      - '9998:8001'
    volumes:
      - redis_data:/data
    networks:
      - redis

networks:
  backend_api:
    name: networks_movie
  redis:
    name: networks_movie

volumes:
  redis_data: